title: MDmp3 Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: "./assets/mdmp3wiki.svg"
color_scheme: mdmp3
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
