title: MDmp3 Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: "./assets/mdmp3wiki.svg"

url: https://cerebralpolicy.github.io/MDmp3-Info/
aux_links:
  Template Repository: https://github.com/cerebralpolicy/MDmp3-Info
